version: "3.7"
services:
  database:     
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    extends:
      file: environment.yml
      service: env
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - highlight
  server:
    container_name: server
    extends:
      file: environment.yml
      service: env
    image: highlightrun/highlight:latest
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8082:8082"
    networks:
      - highlight
    environment: 
      REACT_APP_ONPREM: true
      ONPREM_STATIC_FRONTEND_PATH: "./build"
      PSQL_HOST: "database"
      PSQL_PORT: "5432"
      PSQL_USER: "postgres"
      PSQL_DB: "postgres"
      PSQL_PASSWORD: "password"
volumes:
  data:
networks:
  highlight:
    driver: bridge